# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


SET(CPACK_BINARY_7Z "")
SET(CPACK_BINARY_BUNDLE "")
SET(CPACK_BINARY_CYGWIN "")
SET(CPACK_BINARY_DEB "")
SET(CPACK_BINARY_DRAGNDROP "")
SET(CPACK_BINARY_IFW "")
SET(CPACK_BINARY_NSIS "")
SET(CPACK_BINARY_OSXX11 "")
SET(CPACK_BINARY_PACKAGEMAKER "")
SET(CPACK_BINARY_PRODUCTBUILD "")
SET(CPACK_BINARY_RPM "")
SET(CPACK_BINARY_STGZ "")
SET(CPACK_BINARY_TBZ2 "")
SET(CPACK_BINARY_TGZ "")
SET(CPACK_BINARY_TXZ "")
SET(CPACK_BINARY_TZ "")
SET(CPACK_BINARY_WIX "")
SET(CPACK_BINARY_ZIP "")
SET(CPACK_BUILD_SOURCE_DIRS "C:/Users/vic/Documents/obs-dev/obs-studio;C:/Users/vic/Documents/obs-dev/obs-studio/build64")
SET(CPACK_BUNDLE_ICON "C:/Users/vic/Documents/obs-dev/obs-studio/cmake/osxbundle/obs.icns")
SET(CPACK_BUNDLE_NAME "OBS")
SET(CPACK_BUNDLE_PLIST "C:/Users/vic/Documents/obs-dev/obs-studio/cmake/osxbundle/Info.plist")
SET(CPACK_BUNDLE_STARTUP_COMMAND "C:/Users/vic/Documents/obs-dev/obs-studio/cmake/osxbundle/obslaunch.sh")
SET(CPACK_CMAKE_GENERATOR "Visual Studio 14 2015 Win64")
SET(CPACK_COMPONENTS_ALL "")
SET(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
SET(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
SET(CPACK_CREATE_DESKTOP_LINKS "obs64")
SET(CPACK_GENERATOR "WIX;ZIP")
SET(CPACK_INSTALL_CMAKE_PROJECTS "C:/Users/vic/Documents/obs-dev/obs-studio/build64;obs-studio;ALL;/")
SET(CPACK_INSTALL_PREFIX "C:/Program Files/obs-studio")
SET(CPACK_MODULE_PATH "C:/Users/vic/Documents/obs-dev/obs-studio/cmake/Modules/")
SET(CPACK_NSIS_DISPLAY_NAME "OBS Studio (64bit)")
SET(CPACK_NSIS_INSTALLER_ICON_CODE "")
SET(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
SET(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES64")
SET(CPACK_NSIS_PACKAGE_NAME "OBS Studio (64bit)")
SET(CPACK_OUTPUT_CONFIG_FILE "C:/Users/vic/Documents/obs-dev/obs-studio/build64/CPackConfig.cmake")
SET(CPACK_PACKAGE_DEFAULT_LOCATION "/")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "C:/Program Files/CMake/share/cmake-3.7/Templates/CPack.GenericDescription.txt")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "OBS - Live video and audio streaming and recording software")
SET(CPACK_PACKAGE_EXECUTABLES "obs64;OBS Studio")
SET(CPACK_PACKAGE_FILE_NAME "obs-studio-x64-17.0.2-54-g43e0ecdf")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "OBS Studio (64bit)")
SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "OBSStudio64")
SET(CPACK_PACKAGE_NAME "OBS Studio (64bit)")
SET(CPACK_PACKAGE_RELOCATABLE "true")
SET(CPACK_PACKAGE_VENDOR "obsproject.com")
SET(CPACK_PACKAGE_VERSION "0.0.1")
SET(CPACK_PACKAGE_VERSION_MAJOR "0")
SET(CPACK_PACKAGE_VERSION_MINOR "0")
SET(CPACK_PACKAGE_VERSION_PATCH "1")
SET(CPACK_RESOURCE_FILE_LICENSE "C:/Users/vic/Documents/obs-dev/obs-studio/UI/data/license/gplv2.txt")
SET(CPACK_RESOURCE_FILE_README "C:/Program Files/CMake/share/cmake-3.7/Templates/CPack.GenericDescription.txt")
SET(CPACK_RESOURCE_FILE_WELCOME "C:/Program Files/CMake/share/cmake-3.7/Templates/CPack.GenericWelcome.txt")
SET(CPACK_SET_DESTDIR "OFF")
SET(CPACK_SOURCE_7Z "ON")
SET(CPACK_SOURCE_CYGWIN "")
SET(CPACK_SOURCE_GENERATOR "7Z;ZIP")
SET(CPACK_SOURCE_OUTPUT_CONFIG_FILE "C:/Users/vic/Documents/obs-dev/obs-studio/build64/CPackSourceConfig.cmake")
SET(CPACK_SOURCE_RPM "")
SET(CPACK_SOURCE_TBZ2 "")
SET(CPACK_SOURCE_TGZ "")
SET(CPACK_SOURCE_TXZ "")
SET(CPACK_SOURCE_TZ "")
SET(CPACK_SOURCE_ZIP "ON")
SET(CPACK_SYSTEM_NAME "win64")
SET(CPACK_TOPLEVEL_TAG "win64")
SET(CPACK_WIX_PRODUCT_GUID "ca5bf4fe-7b38-4003-9455-de249d03caac")
SET(CPACK_WIX_SIZEOF_VOID_P "8")
SET(CPACK_WIX_TEMPLATE "C:/Users/vic/Documents/obs-dev/obs-studio/cmake/Modules/WIX.template.in")
SET(CPACK_WIX_UPGRADE_GUID "44c72510-2e8e-489c-8bc0-2011a9631b0b")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "C:/Users/vic/Documents/obs-dev/obs-studio/build64/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
